[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'cd backend && composer install --no-dev --optimize-autoloader',
    'cd frontend && npm install'
]

[phases.build]
cmds = [
    'cd frontend && npm run build',
    'cd backend && php artisan config:cache'
]

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'
